#!/bin/bash
FLAGS="-g -Wall -Wextra -Werror -pedantic"
BTCODES="../bytecodes"
#CONSTANTS
GREEN="\e[32m"
RED="\e[91m"
MAG="\e[5mBlink"
YEL="\e[33m"
RSTCOLOR="\e[0m"
CYAN="\e[96m"
BOLDMAG="\e[1m\e[95m"

# COMENTARIO PARA SERGIO: Yo se que se puede hacer más eficiente pero eun no se como xd

# ------------------------------------- #
# UNIT TEST PINT (Uncomment to use them)
# ------------------------------------- #

# printf "${CYAN}Test opcode: ${BOLDMAG}PINT${RSTCOLOR}\n"
# gcc $FLAGS ../*.c -o test
# printf "${YEL}File: ${BOLDMAG} 0-pint.m ${RSTCOLOR}\n"
# ./test $BTCODES/pint-files/0-pint.m
# printf "${YEL}File: ${BOLDMAG} 1-pint.m ${RSTCOLOR}\n"
# ./test $BTCODES/pint-files/1-pint.m
# printf "${YEL}File: ${BOLDMAG} 2-pint.m ${RSTCOLOR}\n"
# ./test $BTCODES/pint-files/2-pint.m
# printf "${YEL}File: ${BOLDMAG} 3-pint.m ${RSTCOLOR}\n"
# ./test $BTCODES/pint-files/3-pint.m

# -------------- #
# UNIT TEST POP (Uncomment to use them)
# -------------- #

# printf "${CYAN} Test opcode: ${BOLDMAG}POP ${RSTCOLOR}\n"
# gcc $FLAGS ../*.c -o test
# printf "${YEL}File: ${BOLDMAG} 0-pop.m ${RSTCOLOR}\n"
# ./test $BTCODES/pop-files/0-pop.m
# printf "${YEL}File: ${BOLDMAG} 1-pop.m ${RSTCOLOR}\n"
# ./test $BTCODES/pop-files/1-pop.m
# printf "${YEL}File: ${BOLDMAG} 2-pop.m ${RSTCOLOR}\n"
# ./test $BTCODES/pop-files/2-pop.m
# printf "${YEL}File: ${BOLDMAG} 3-pop.m ${RSTCOLOR}\n"
# ./test $BTCODES/pop-files/3-pop.m

# ------------------------------------- #
# UNIT TEST SWAP (Uncomment to use them)
# ------------------------------------- #

# printf "${CYAN} Test opcode: ${BOLDMAG}SWAP ${RSTCOLOR}\n"
# gcc $FLAGS ../*.c -o test
# printf "${YEL}File: ${BOLDMAG} 0-swap.m ${RSTCOLOR}\n"
# ./test $BTCODES/swap-files/0-swap.m
# printf "${YEL}File: ${BOLDMAG} 1-swap.m ${RSTCOLOR}\n"
# ./test $BTCODES/swap-files/1-swap.m
# printf "${YEL}File: ${BOLDMAG} 2-swap.m ${RSTCOLOR}\n"
# ./test $BTCODES/swap-files/2-swap.m
# printf "${YEL}File: ${BOLDMAG} 3-swap.m ${RSTCOLOR}\n"
# ./test $BTCODES/swap-files/3-swap.m
# printf "${YEL}File: ${BOLDMAG} 4-swap.m ${RSTCOLOR}\n"
# ./test $BTCODES/swap-files/4-swap.m


# ------------------------------------- #
# UNIT TEST ADD (Uncomment to use them)
# ------------------------------------- #

# printf "${CYAN} Test opcode: ${BOLDMAG}ADD ${RSTCOLOR}\n"
# gcc $FLAGS ../*.c -o test
# printf "${YEL}File: ${BOLDMAG} 0-add.m ${RSTCOLOR}\n"
# ./test $BTCODES/add-files/0-add.m
# printf "${YEL}File: ${BOLDMAG} 1-add.m ${RSTCOLOR}\n"
# ./test $BTCODES/add-files/1-add.m
# printf "${YEL}File: ${BOLDMAG} 2-add.m ${RSTCOLOR}\n"
# ./test $BTCODES/add-files/2-add.m
# printf "${YEL}File: ${BOLDMAG} 3-add.m ${RSTCOLOR}\n"
# ./test $BTCODES/add-files/3-add.m
# printf "${YEL}File: ${BOLDMAG} 4-add.m ${RSTCOLOR}\n"
# ./test $BTCODES/add-files/4-add.m

# ------------------------------------- #
# UNIT TEST NOP (Uncomment to use them)
# ------------------------------------- #

# printf "${CYAN} Test opcode: ${BOLDMAG}NOP ${RSTCOLOR}\n"
# gcc $FLAGS ../*.c -o test
# printf "${YEL}File: ${BOLDMAG} 0-nop.m ${RSTCOLOR}\n"
# ./test $BTCODES/nop-files/0-nop.m
# printf "${YEL}File: ${BOLDMAG} 1-nop.m ${RSTCOLOR}\n"
# ./test $BTCODES/nop-files/1-nop.m
# printf "${YEL}File: ${BOLDMAG} 2-nop.m ${RSTCOLOR}\n"
# ./test $BTCODES/nop-files/2-nop.m
# printf "${YEL}File: ${BOLDMAG} 3-nop.m ${RSTCOLOR}\n"
# ./test $BTCODES/nop-files/3-nop.m
# printf "${YEL}File: ${BOLDMAG} 4-nop.m ${RSTCOLOR}\n"
# ./test $BTCODES/nop-files/4-nop.m
